replicaCount: 1

image:
  repository: digital-queue-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://my-postgresql:5432/postgres?currentSchema=digital_queue
  - name: SPRING_DATASOURCE_USERNAME
    value: postgres
  - name: SPRING_DATASOURCE_PASSWORD
    value: admin
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: my-kafka:9092

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false